version: "3"
services:
  service:
    build: ./
    ports:
      - "7000:7000"
    Links: mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
